import { MarketEntry } from "./types";

// Sample sold-listing comps and population data for a curated set of
// well-known sports cards. This is illustrative sample data, not live
// market or grading-company data.
const POP_AS_OF = "2026-08-01";

export const MARKET_DATABASE: MarketEntry[] = [
  {
    compKey: "trout-2011-topps-update-us175",
    player: "Mike Trout",
    sport: "Baseball",
    year: "2011",
    brand: "Topps",
    setName: "Update Series",
    cardNumber: "US175",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-18", price: 3450, platform: "eBay", grade: "PSA 10" },
      { date: "2026-08-05", price: 3200, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-07-22", price: 3600, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-09", price: 3100, platform: "Goldin", grade: "PSA 10" },
      { date: "2026-06-24", price: 2950, platform: "eBay", grade: "PSA 10" },
      { date: "2026-06-02", price: 2800, platform: "eBay", grade: "PSA 10" },
      { date: "2026-05-11", price: 2700, platform: "PWCC", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 21432, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 96, note: "Perennial MVP-caliber numbers keep this near-lock in fan discussion" },
  },
  {
    compKey: "ohtani-2018-bowman-chrome-btc1",
    player: "Shohei Ohtani",
    sport: "Baseball",
    year: "2018",
    brand: "Bowman",
    setName: "Chrome",
    cardNumber: "BTC-1",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "9",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-20", price: 610, platform: "eBay", grade: "PSA 9" },
      { date: "2026-08-09", price: 585, platform: "eBay", grade: "PSA 9" },
      { date: "2026-07-27", price: 640, platform: "Goldin", grade: "PSA 9" },
      { date: "2026-07-14", price: 560, platform: "eBay", grade: "PSA 9" },
      { date: "2026-06-30", price: 520, platform: "PWCC", grade: "PSA 9" },
      { date: "2026-06-10", price: 495, platform: "eBay", grade: "PSA 9" },
    ],
    population: { gradingCompany: "PSA", grade: "9", popAtGrade: 3187, popHigher: 1402, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 98, note: "Unanimous first-ballot territory in most fan and analyst chatter" },
  },
  {
    compKey: "acuna-2018-topps-chrome-193",
    player: "Ronald Acuña Jr.",
    sport: "Baseball",
    year: "2018",
    brand: "Topps",
    setName: "Chrome",
    cardNumber: "193",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-15", price: 410, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-30", price: 395, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-11", price: 430, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-06-19", price: 380, platform: "eBay", grade: "PSA 10" },
      { date: "2026-05-28", price: 360, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 5614, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 78, note: "Strong trajectory, though injury history tempers some chatter" },
  },
  {
    compKey: "skenes-2023-bowman-chrome-draft-bdc-50",
    player: "Paul Skenes",
    sport: "Baseball",
    year: "2023",
    brand: "Bowman",
    setName: "Chrome Draft",
    cardNumber: "BDC-50",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-21", price: 245, platform: "eBay", grade: "PSA 10" },
      { date: "2026-08-06", price: 260, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-19", price: 225, platform: "Goldin", grade: "PSA 10" },
      { date: "2026-06-28", price: 210, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 2118, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 35, note: "Way too early to project, but electric rookie chatter has fans speculating" },
  },
  {
    compKey: "mantle-1952-topps-311",
    player: "Mickey Mantle",
    sport: "Baseball",
    year: "1952",
    brand: "Topps",
    setName: "Topps",
    cardNumber: "311",
    parallel: "Base",
    gradingCompany: "PSA",
    grade: "5",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-12", price: 178000, platform: "Heritage Auctions", grade: "PSA 5" },
      { date: "2026-06-20", price: 165000, platform: "Goldin", grade: "PSA 5" },
      { date: "2026-04-02", price: 152000, platform: "Heritage Auctions", grade: "PSA 5" },
      { date: "2026-01-15", price: 148000, platform: "PWCC", grade: "PSA 5" },
    ],
    population: { gradingCompany: "PSA", grade: "5", popAtGrade: 487, popHigher: 211, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "Inducted 1974 — a Hall of Fame lock" },
  },
  {
    compKey: "jordan-1986-fleer-57",
    player: "Michael Jordan",
    sport: "Basketball",
    year: "1986",
    brand: "Fleer",
    setName: "Fleer",
    cardNumber: "57",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "8",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏀",
    sales: [
      { date: "2026-08-19", price: 24500, platform: "Goldin", grade: "PSA 8" },
      { date: "2026-07-25", price: 22800, platform: "PWCC", grade: "PSA 8" },
      { date: "2026-06-14", price: 26100, platform: "Heritage Auctions", grade: "PSA 8" },
      { date: "2026-05-02", price: 21000, platform: "eBay", grade: "PSA 8" },
    ],
    population: { gradingCompany: "PSA", grade: "8", popAtGrade: 1214, popHigher: 623, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "Inducted 2009 — universally regarded as a lock" },
  },
  {
    compKey: "lebron-2003-topps-chrome-111",
    player: "LeBron James",
    sport: "Basketball",
    year: "2003",
    brand: "Topps",
    setName: "Chrome",
    cardNumber: "111",
    parallel: "Base Rookie",
    gradingCompany: "BGS",
    grade: "9.5",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏀",
    sales: [
      { date: "2026-08-17", price: 5200, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-08-02", price: 4950, platform: "PWCC", grade: "BGS 9.5" },
      { date: "2026-07-16", price: 5400, platform: "Goldin", grade: "BGS 9.5" },
      { date: "2026-06-25", price: 4700, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-05-30", price: 4600, platform: "eBay", grade: "BGS 9.5" },
    ],
    population: { gradingCompany: "BGS", grade: "9.5", popAtGrade: 1108, popHigher: 96, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 99, note: "Widely considered a first-ballot lock in fan chatter" },
  },
  {
    compKey: "wembanyama-2023-panini-prizm-turbo-1",
    player: "Victor Wembanyama",
    sport: "Basketball",
    year: "2023",
    brand: "Panini",
    setName: "Prizm",
    cardNumber: "1",
    parallel: "Silver Prizm",
    gradingCompany: "BGS",
    grade: "9.5",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏀",
    sales: [
      { date: "2026-08-22", price: 890, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-08-08", price: 950, platform: "Goldin", grade: "BGS 9.5" },
      { date: "2026-07-21", price: 820, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-06-29", price: 780, platform: "PWCC", grade: "BGS 9.5" },
      { date: "2026-06-05", price: 860, platform: "eBay", grade: "BGS 9.5" },
    ],
    population: { gradingCompany: "BGS", grade: "9.5", popAtGrade: 604, popHigher: 41, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 42, note: "Extremely early, but generational-talent buzz already speculates HOF" },
  },
  {
    compKey: "clark-2024-panini-prizm-wnba-1",
    player: "Caitlin Clark",
    sport: "Basketball",
    year: "2024",
    brand: "Panini",
    setName: "Prizm WNBA",
    cardNumber: "1",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏀",
    sales: [
      { date: "2026-08-23", price: 1350, platform: "eBay", grade: "PSA 10" },
      { date: "2026-08-10", price: 1480, platform: "Goldin", grade: "PSA 10" },
      { date: "2026-07-28", price: 1250, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-05", price: 1600, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-06-12", price: 1150, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 1342, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 55, note: "Historic rookie impact fuels active HOF chatter despite a short track record" },
  },
  {
    compKey: "mahomes-2017-panini-prizm-269",
    player: "Patrick Mahomes",
    sport: "Football",
    year: "2017",
    brand: "Panini",
    setName: "Prizm",
    cardNumber: "269",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏈",
    sales: [
      { date: "2026-08-20", price: 6800, platform: "eBay", grade: "PSA 10" },
      { date: "2026-08-04", price: 7200, platform: "Goldin", grade: "PSA 10" },
      { date: "2026-07-17", price: 6500, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-06-26", price: 7000, platform: "eBay", grade: "PSA 10" },
      { date: "2026-06-01", price: 6300, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 4213, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 95, note: "Multiple championships keep this near-consensus in fan discussion" },
  },
  {
    compKey: "brady-2000-playoff-contenders-144",
    player: "Tom Brady",
    sport: "Football",
    year: "2000",
    brand: "Playoff Contenders",
    setName: "Contenders",
    cardNumber: "144",
    parallel: "Autograph Rookie",
    gradingCompany: "PSA",
    grade: "9",
    certNumber: "",
    isAutograph: true,
    autographCompany: "PSA/DNA",
    autographGrade: "",
    imageEmoji: "🏈",
    sales: [
      { date: "2026-08-14", price: 210000, platform: "Heritage Auctions", grade: "PSA 9" },
      { date: "2026-06-18", price: 198000, platform: "Goldin", grade: "PSA 9" },
      { date: "2026-04-09", price: 225000, platform: "PWCC", grade: "PSA 9" },
    ],
    population: { gradingCompany: "PSA", grade: "9", popAtGrade: 68, popHigher: 12, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "First-ballot inductee — a Hall of Fame lock" },
  },
  {
    compKey: "jefferson-2020-panini-prizm-398",
    player: "Justin Jefferson",
    sport: "Football",
    year: "2020",
    brand: "Panini",
    setName: "Prizm",
    cardNumber: "398",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏈",
    sales: [
      { date: "2026-08-16", price: 480, platform: "eBay", grade: "PSA 10" },
      { date: "2026-08-01", price: 510, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-13", price: 460, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-06-22", price: 495, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 3096, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 60, note: "Elite peak production, but career length is still debated in chatter" },
  },
  {
    compKey: "griffey-1989-upper-deck-1",
    player: "Ken Griffey Jr.",
    sport: "Baseball",
    year: "1989",
    brand: "Upper Deck",
    setName: "Upper Deck",
    cardNumber: "1",
    parallel: "Base Rookie",
    gradingCompany: "SGC",
    grade: "9",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-11", price: 320, platform: "eBay", grade: "SGC 9" },
      { date: "2026-07-24", price: 305, platform: "eBay", grade: "SGC 9" },
      { date: "2026-06-30", price: 340, platform: "PWCC", grade: "SGC 9" },
      { date: "2026-05-22", price: 290, platform: "eBay", grade: "SGC 9" },
    ],
    population: { gradingCompany: "SGC", grade: "9", popAtGrade: 2940, popHigher: 615, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "Inducted 2016 with a record vote share" },
  },
  {
    compKey: "brown-2000-playoff-contenders",
    player: "Kobe Bryant",
    sport: "Basketball",
    year: "1996",
    brand: "Topps Chrome",
    setName: "Topps Chrome",
    cardNumber: "138",
    parallel: "Base Rookie",
    gradingCompany: "BGS",
    grade: "9",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏀",
    sales: [
      { date: "2026-08-13", price: 8900, platform: "Goldin", grade: "BGS 9" },
      { date: "2026-07-20", price: 9400, platform: "Heritage Auctions", grade: "BGS 9" },
      { date: "2026-06-15", price: 8300, platform: "PWCC", grade: "BGS 9" },
      { date: "2026-05-10", price: 8700, platform: "eBay", grade: "BGS 9" },
    ],
    population: { gradingCompany: "BGS", grade: "9", popAtGrade: 511, popHigher: 89, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "Inducted 2020 — a lock" },
  },
  {
    compKey: "ripken-1982-topps-traded-98t",
    player: "Cal Ripken Jr.",
    sport: "Baseball",
    year: "1982",
    brand: "Topps Traded",
    setName: "Topps Traded",
    cardNumber: "98T",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "8",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "⚾",
    sales: [
      { date: "2026-08-09", price: 640, platform: "eBay", grade: "PSA 8" },
      { date: "2026-07-15", price: 610, platform: "eBay", grade: "PSA 8" },
      { date: "2026-06-08", price: 670, platform: "PWCC", grade: "PSA 8" },
    ],
    population: { gradingCompany: "PSA", grade: "8", popAtGrade: 612, popHigher: 341, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 100, note: "Inducted 2007 — a lock" },
  },
  {
    compKey: "purdy-2022-panini-prizm-343",
    player: "Brock Purdy",
    sport: "Football",
    year: "2022",
    brand: "Panini",
    setName: "Prizm",
    cardNumber: "343",
    parallel: "Base Rookie",
    gradingCompany: "SGC",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏈",
    sales: [
      { date: "2026-08-18", price: 165, platform: "eBay", grade: "SGC 10" },
      { date: "2026-08-03", price: 178, platform: "eBay", grade: "SGC 10" },
      { date: "2026-07-10", price: 152, platform: "PWCC", grade: "SGC 10" },
      { date: "2026-06-14", price: 140, platform: "eBay", grade: "SGC 10" },
    ],
    population: { gradingCompany: "SGC", grade: "10", popAtGrade: 3218, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 18, note: "Speculative early buzz — far too soon to seriously project" },
  },
  {
    compKey: "crosby-2005-upper-deck-young-guns-201",
    player: "Sidney Crosby",
    sport: "Hockey",
    year: "2005",
    brand: "Upper Deck",
    setName: "Young Guns",
    cardNumber: "201",
    parallel: "Base Rookie",
    gradingCompany: "PSA",
    grade: "10",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏒",
    sales: [
      { date: "2026-08-15", price: 2100, platform: "eBay", grade: "PSA 10" },
      { date: "2026-07-28", price: 1950, platform: "PWCC", grade: "PSA 10" },
      { date: "2026-07-02", price: 2250, platform: "Goldin", grade: "PSA 10" },
      { date: "2026-06-10", price: 1900, platform: "eBay", grade: "PSA 10" },
    ],
    population: { gradingCompany: "PSA", grade: "10", popAtGrade: 612, popHigher: 0, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 99, note: "Sustained excellence across two decades keeps this a near-lock in fan chatter" },
  },
  {
    compKey: "mcdavid-2015-upper-deck-young-guns-201",
    player: "Connor McDavid",
    sport: "Hockey",
    year: "2015",
    brand: "Upper Deck",
    setName: "Young Guns",
    cardNumber: "201",
    parallel: "Base Rookie",
    gradingCompany: "BGS",
    grade: "9.5",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🏒",
    sales: [
      { date: "2026-08-20", price: 1450, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-08-01", price: 1600, platform: "Goldin", grade: "BGS 9.5" },
      { date: "2026-07-14", price: 1380, platform: "eBay", grade: "BGS 9.5" },
      { date: "2026-06-19", price: 1500, platform: "PWCC", grade: "BGS 9.5" },
    ],
    population: { gradingCompany: "BGS", grade: "9.5", popAtGrade: 894, popHigher: 61, asOf: POP_AS_OF },
    hallOfFameChance: { percent: 97, note: "Widely regarded as a generational talent, already common HOF chatter" },
  },
  {
    compKey: "gpk-1985-topps-series1-adam-bomb-8a",
    player: "Adam Bomb",
    sport: "Other",
    year: "1985",
    brand: "Topps",
    setName: "Garbage Pail Kids Series 1",
    cardNumber: "8a",
    parallel: "Base",
    gradingCompany: "PSA",
    grade: "9",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🗑️",
    sales: [
      { date: "2026-08-17", price: 145, platform: "eBay", grade: "PSA 9" },
      { date: "2026-07-30", price: 160, platform: "eBay", grade: "PSA 9" },
      { date: "2026-07-05", price: 130, platform: "Goldin", grade: "PSA 9" },
      { date: "2026-06-08", price: 150, platform: "eBay", grade: "PSA 9" },
    ],
    population: { gradingCompany: "PSA", grade: "9", popAtGrade: 1840, popHigher: 320, asOf: POP_AS_OF },
    hallOfFameChance: null,
  },
  {
    compKey: "gpk-1985-topps-series1-nasty-nick-1a",
    player: "Nasty Nick",
    sport: "Other",
    year: "1985",
    brand: "Topps",
    setName: "Garbage Pail Kids Series 1",
    cardNumber: "1a",
    parallel: "Base",
    gradingCompany: "PSA",
    grade: "8",
    certNumber: "",
    isAutograph: false,
    autographCompany: "",
    autographGrade: "",
    imageEmoji: "🗑️",
    sales: [
      { date: "2026-08-12", price: 310, platform: "eBay", grade: "PSA 8" },
      { date: "2026-07-22", price: 285, platform: "Heritage Auctions", grade: "PSA 8" },
      { date: "2026-06-27", price: 330, platform: "eBay", grade: "PSA 8" },
    ],
    population: { gradingCompany: "PSA", grade: "8", popAtGrade: 940, popHigher: 410, asOf: POP_AS_OF },
    hallOfFameChance: null,
  },
];
